/**
 * @file KStream.h
 * @author Shane Girolamo
 *
 * @brief Public interface for the KStream Abstract Data Type (ADT).
 *
 * This module implements a symmetric-key stream cipher based on a
 * pseudorandom keystream generator. The keystream is produced from an
 * 8-byte (64-bit) binary key and used to translate bytes between
 * plaintext and ciphertext via XOR.
 *
 * ----------------------------------------------------------------------------
 * DESIGN CHOICES
 * ----------------------------------------------------------------------------
 * 1. The client (main program) is responsible for opening the key file,
 *    reading the 8-byte binary key into a uint64_t, and passing it to
 *    ks_create(). The KStream module does not perform any file I/O.
 *
 * 2. In ks_translate(), the **client allocates the output buffer**.
 *    The function fills it with translated bytes. This avoids repeated
 *    malloc/free calls and allows the client to reuse buffers.
 *
 * 3. The KStream struct is intentionally opaque. Clients cannot see the
 *    internal fields or manipulate the algorithm state.
 */

#ifndef KSTREAM_H
#define KSTREAM_H

#include <stddef.h> // size_t
#include <stdint.h> // uint64_t, uint8_t

/** Opaque data type for the KStream object. */
typedef struct KStream KStream;

/**
 * @brief Create and initialize a new KStream instance.
 *
 * Initializes the internal S array (0–255), performs the key-scheduling
 * algorithm (KSA), and primes the stream by discarding the first 1024
 * generated bytes. The returned object must later be destroyed with
 * ks_destroy().
 *
 * @param key64  A 64-bit value representing the eight-byte binary key.
 *
 * @return A pointer to a fully-initialized KStream instance.
 *
 * @pre  The caller has already read a valid 8-byte binary key.
 * @post A heap-allocated KStream is returned; caller must free it.
 */
KStream *ks_create(uint64_t key64);

/**
 * @brief Destroy a KStream instance and free all associated memory.
 *
 * @param ks  The KStream instance to be destroyed.
 *
 * @pre  ks is a pointer returned by ks_create().
 * @post All memory allocated for the instance is released.
 */
void ks_destroy(KStream *ks);

/**
 * @brief Translate input bytes to output bytes using the KStream.
 *
 * The translation is symmetric: applying ks_translate() to ciphertext
 * produces plaintext, and applying it to plaintext produces ciphertext.
 *
 * The caller allocates both the input and output buffers. The output
 * buffer must be at least `num` bytes long.
 *
 * @param ks        A valid KStream instance.
 * @param in        Pointer to input buffer containing plaintext or ciphertext.
 * @param out       Pointer to output buffer (must be pre-allocated).
 * @param num       Number of bytes to translate.
 *
 * @pre  ks is initialized. `in` and `out` point to valid buffers.
 * @pre  `out` has room for at least `num` bytes.
 *
 * @post `out` contains the XOR-translated bytes.
 *
 * @return void
 */
void ks_translate(KStream *ks, const uint8_t *in, uint8_t *out, size_t num);

#endif // KSTREAM_H